### ISSUE TITLE
Ruby group capstone - set up your Kanban board

### ISSUE THREAD

**Issue by Meri-MG** [Meri-MG/Ruby-Group-Capstone#30]
#### We are a team of four

The project https://github.com/Meri-MG/Ruby-Group-Capstone/projects/1
Please, use the FullScreen mode to review the cards or copy them into the new tab, otherwise, GitHub is acting weird. Thanks. 

Team 1 - Ellis Ngona
Team 2 - Meri Gogichashvili
Team 3 - Lilian Moraa
Team 4 - Bohdan Shcherbak

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Meri-MG, @lily-coder, @mwanawabangona and @akucintavalent,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted an Issue that contains link to your repo whereas you are expected to provide link to the Kanban board itself

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi team,

Good job so far!
✔️ All group tasks are assigned.
✔️ All tasks have complexity points
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] **When (re)assigning these tasks, kindly ensure that no member has 5 points (`[Xpt]`) more than another team member**

- [x] **According to your issue, @mwanawabangona is Team member 1. I think there is a mix-up between tasks for members 1 and 2. He is missing the tasks that take care of the following:**

  ![ellis-1](https://user-images.githubusercontent.com/36542986/158190378-0a761509-5bef-418f-a20e-555dfd0529f4.jpg)
  <hr />

  ![ellis-2](https://user-images.githubusercontent.com/36542986/158191087-425f5675-6004-4534-9709-047e42904097.jpg)

- [x] **@Meri-MG is team member 2. She is missing tasks relating to the following:**

  ![meri-1](https://user-images.githubusercontent.com/36542986/158192257-0447b239-6784-44d8-9945-76d54094b514.jpg)

- [x] **Team member 3, @lily-coder is missing the following tasks:**

  ![lilian-1](https://user-images.githubusercontent.com/36542986/158192406-9a2edbbc-97a1-40e6-a2b0-c24954e61547.jpg)
  <hr />  

  ![lilian-2](https://user-images.githubusercontent.com/36542986/158192417-327a3588-29b4-4982-b5e4-a8c2eb3eae55.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
